server:
  port: 8084
  compression:
        enabled: true
        min-response-size: 1
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:9527/demo?useUnicode=true&amp;characterEncoding=UTF-8&useSSL=false
        username: name
        password: password
        initialSize: 1
        minIdle: 1
        maxActive: 5
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,wall,log4j
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
redis:
    host: 127.0.0.1
    port: 56379
    dbindex: 0
    timeout: 0


